backend:
  name: github
  repo: jonathanatn/TestNetlify   # your GitHub repo
  branch: main
  auth_type: "oauth"               # added for GitHub Pages authentication

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "docs"
    label: "Docs"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
